import Navbar2 from "../components/Navbar2";
import Footer from "../components/Footer";
import "./styles/globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // icons: [
  //   {
  //     rel: 'icon',
  //     type: 'image/png',
  //     sizes: '32x32',
  //     url: '/favicon.ico',
  //   },
  // {
  //   rel: 'icon',
  //   type: 'image/png',
  //   sizes: '16x16',
  //   url: '/favicon/favicon-16x16.png',
  // },
  // {
  //   rel: 'apple-touch-icon',
  //   sizes: '180x180',
  //   url: '/favicon/apple-touch-icon.png',
  // },
  // ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar2 />
        {children}
        <Footer />
      </body>
    </html>
  );
}
